# Generated by Django 2.1.3 on 2019-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fd_id', models.CharField(max_length=200, unique=True)),
                ('fd_name', models.CharField(max_length=100)),
                ('fd_type', models.CharField(max_length=100)),
                ('fd_count', models.IntegerField()),
                ('fd_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fd_picture', models.CharField(default='null', max_length=256)),
                ('fd_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='foodtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd_type_id', models.CharField(max_length=20)),
                ('fd_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True)),
                ('order_num', models.CharField(max_length=100)),
                ('order_state', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('goods_id', models.CharField(max_length=100)),
                ('goods_count', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reserved_State', models.IntegerField(null=True)),
                ('reserved_Time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True)),
                ('userName', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=100)),
                ('conn', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
            ],
        ),
    ]
