# Generated by Django 2.1.3 on 2019-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='openid',
            field=models.CharField(max_length=100),
        ),
    ]
