# Generated by Django 2.1.3 on 2019-03-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six0', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='identifier',
            field=models.CharField(default='None', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
