# Generated by Django 2.1.3 on 2019-03-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('six0', '0004_auto_20190301_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
