# Generated by Django 2.1.3 on 2019-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six0', '0005_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('session', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
