# Generated by Django 2.1.3 on 2019-03-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('six0', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
